### ISSUE TITLE
International days

### ISSUE THREAD

**Issue by Adman** [novapost/workalendar#107]
It will be cool, if there are also international days added to this repository. What do you think?

**Comment by Natim** [comment]
What do you mean by international days?

**Comment by Adman** [comment]
For instance St. Valentine's Day, Mothers Day, Day of women, Day of programmers, Day of Earth etc.....

**Comment by Adman** [comment]
@brunobord Any thoughts ?

**Comment by brunobord** [comment]
@Adman: These international days are out of scope for workalendar. The point of this lib is not to gather every special day in every calendar, it's to define and compute working days and non-working days. AFAICT, Mothers Day or St Valentine Day is not a holiday (or I haven't seen it in any calendar so far). If it is, it has to be defined in this specific calendar. If it's used more than once, it could be defined in a InternationValentineDayMixin for example, that add February 14th to the static non-working days.

I'm sorry, but I'll have to close this as a WONTFIX.
