### ISSUE TITLE
SouthAfrica weekends calculated wrong

### ISSUE THREAD

**Issue by renierdbruyn** [novapost/workalendar#98]
Currently in the library it only uses Sunday when getting the weekends, When in fact it should be using Saturday as well..

**Comment by brunobord** [comment]
I have to disagree here:

```
>>> import datetime
>>> from workalendar.africa import SouthAfrica
>>> cal = SouthAfrica()
>>> cal.is_working_day(datetime.date(2015, 6, 12))  # friday
True
>>> cal.is_working_day(datetime.date(2015, 6, 13))  # saturday
False
>>> cal.is_working_day(datetime.date(2015, 6, 14))  # sunday
False
```

How did you manage to get a saturday as a working day using SouthAfrica calendar?

**Comment by renierdbruyn** [comment]
This was a post directed at one of the forks of this project - [calendra](https://github.com/jaraco/calendra) - this was version 1.1.2 at the time and do not know if it is fixed as yet...

I was desperate to get a library that would get the working days, such as yours, but which was active(at the time this repo was not active)... I have accidentally directed the question/issue on the wrong repo... I apologise for this... I ended up using your project (It works great btw :+1: :smile: ).

**Comment by Natim** [comment]
What made you think this project was not active?

**Comment by renierdbruyn** [comment]
At the time that I created the issue, I looked at the pull requests - there where, I think 2 outstanding pull requests that has been there for a month or two. And the last update to the repo was quite a while ago. I can not remember exact times, but it seemed as if this project was standing still...

**Comment by brunobord** [comment]
@renierdbruyn "I AINT'NT DEAD" ;o)

But you're probably right, this project deserves more care and I'm so sorry not to be able to give it enough time.
Anyway, I'm glad workalendar fits your needs, and that you're using it.

/me is now looking for settings to get more alerts on issues
